FORMAT: 1A
HOST: http://data.gizwits.com

# Datasync API

# Group 设备信息接口

## 设备信息 [/1/classes/device_info{?where}]

### 添加设备信息 [POST]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {
              "did": "z9fJgw6LeZBsuFeV9PMbLA",
              "mac": "001122334455",
              "name": "my_socket",
              "capacity": 100,
              "watts": 1000,
              "city": "广州",
              "username": "bob"
            }

+ Response 201 (application/json)

    + Body
    
            {
              "createdAt": "2011-08-20T02:06:57.931Z",
              "objectId": "Ed1nuqPvcm"
            }

### 获取用户设备列表 [GET]

+ Parameters
    + where (request, string, `{"username":bob}`)

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}

+ Response 200 (application/json)

    + Body
    
            {
                "results": [
                    {
                        "city": "广州",
                        "watts": 1000,
                        "capacity": 100,
                        "name": "my_socket",
                        "objectId": "5424c7b358ebfc3ec01cbf5d",
                        "did": "z9fJgw6LeZBsuFeV9PMbLA",
                        "mac": "001122334455",
                        "updatedAt": "2014-09-26T01:57:23.189Z",
                        "createdAt": "2014-09-26T01:56:03.266Z"
                    }
                ]
            }


## 设备信息 [/1/classes/device_info/{objectId}]

+ Parameters
    + objectId (required, string, `Ed1nuqPvcm`)

### 修改设备信息 [PUT]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {
              "city": "广州"
            }

+ Response 200 (application/json)

    + Body
    
            {
              "updatedAt": "2011-08-20T02:06:57.931Z"
            }

### 删除设备信息 [DELETE]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

+ Response 200 (application/json)

    + Body
    
            {}


# Group 用电信息接口

## 用电信息接口 [/1/power_usage{?did,date,week,month,year}]

+ Parameters
    + where (request, string) ... json 格式的查询条件，如 {"did": "aJizfAaZTZf92UGyypeJb3", "date": "2014-09-26"}
    + limit (optional, number, `20`) ... 返回数据的条数
    + order (optional, string, `-date`) ... 按日期降序排序
    + keys (optional, string, `kwhr,did,date`) ... 显示的字段

### 查询设备用电信息 [GET]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}

+ Response 200 (application/json)

    + Body
    
            {
                "results": [
                    {
                        "hourly": {
                            "15": 0
                        },
                        "objectId": "54251bb458ebfc3ec01cbf66",
                        "did": "aJizfAaZTZf92UGyypeJb3",
                        "kwhr": 0,
                        "updatedAt": "2014-09-26T07:54:28.105Z",
                        "date": "2014-09-26",
                        "createdAt": "2014-09-26T07:54:28.105Z"
                    }
                ]
            }
