FORMAT: 1A
HOST: http://data.gizwits.com

# Datasync API

# Group 设备信息接口

## 设备信息 [/1/classes/device_info{?where}]

### 添加设备信息 [POST]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {
              "did": "z9fJgw6LeZBsuFeV9PMbLA",
              "mac": "001122334455",
              "passcode": "pass",
              "name": "my_socket",
              "capacity": 100,
              "watts": 1000,
              "city": "广州",
              "username": "bob"
            }

+ Response 201 (application/json)

    + Body
    
            {
              "createdAt": "2011-08-20T02:06:57.931Z",
              "objectId": "Ed1nuqPvcm"
            }

### 获取用户设备列表 [GET]

+ Parameters
    + where (request, string, `{"username":bob}`)

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}

+ Response 200 (application/json)

    + Body
    
            {
                "results": [
                    {
                        "city": "广州",
                        "watts": 1000,
                        "capacity": 100,
                        "name": "my_socket",
                        "objectId": "5424c7b358ebfc3ec01cbf5d",
                        "did": "z9fJgw6LeZBsuFeV9PMbLA",
                        "passcode": "pass",
                        "mac": "001122334455",
                        "updatedAt": "2014-09-26T01:57:23.189Z",
                        "createdAt": "2014-09-26T01:56:03.266Z"
                    }
                ]
            }


## 设备信息 [/1/classes/device_info/{objectId}]

+ Parameters
    + objectId (required, string, `Ed1nuqPvcm`)

### 修改设备信息 [PUT]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {
              "city": "广州"
            }

+ Response 200 (application/json)

    + Body
    
            {
              "updatedAt": "2011-08-20T02:06:57.931Z"
            }

### 删除设备信息 [DELETE]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

+ Response 200 (application/json)

    + Body
    
            {}


# Group 用电信息接口

## 用电信息接口 [/1/power_usage{?did,date,week,month,year}]

+ Parameters
    + did (required, string, `did`)
    + date (optional, string, `2014-10-10`)
    + week (optional, int, `42`)
    + month (optional, int, `10`)
    + year (optional, int, `2014`)

### 获取用电信息 [GET]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

+ Response 200 (application/json)

    + Body
    
            {        
                "date": "2014-10-10",
                "did": "DNsBG72j3ntNkRyFuNAHiC",
                "report": {
                    "0": 0,
                    "1": 0,
                    "2": 0,
                    "3": 0,
                    "4": 0,
                    "5": 0,
                    "6": 0,
                    "7": 0,
                    "8": 0,
                    "9": 0,
                    "10": 0,
                    "11": 0,
                    "12": 0,
                    "13": 0,
                    "14": 0,
                    "15": 0,
                    "16": 0,
                    "17": 0,
                    "18": 0,
                    "19": 0,
                    "20": 0,
                    "21": 0,
                    "22": 0,
                    "23": 0
                }
            }        

## 电费信息 [/1/money_saved{?did}]

+ Parameters
    + did (required, string, `did`)

### 获取电费信息 [GET]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

+ Response 200 (application/json)

    + Body

            {
                "did": "DNsBG72j3ntNkRyFuNAHiC",
                "total": 0,
                "today": 0,
                "month": 0
            }

## 重置设备用电及电费信息 [/1/reset_device{?did}]

### 重置设备用电及电费信息 [GET]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

+ Response 200 (application/json)

    + Body

            {}
