FORMAT: 1A
HOST: http://data.gizwits.com

# Datasync API

# Group 设备信息接口

## 设备信息 [/1/classes/device_info{?where}]

### 添加设备信息 [POST]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {
              "did": "z9fJgw6LeZBsuFeV9PMbLA",
              "name": "my_socket",
              "capacity": 100,
              "watts": 1000,
              "city": "广州",
              "username": "bob"
            }

+ Response 201 (application/json)

    + Body
    
            {
              "createdAt": "2011-08-20T02:06:57.931Z",
              "objectId": "Ed1nuqPvcm"
            }

### 获取用户设备列表 [GET]

+ Parameters
    + where (request, string, `{"username":bob}`)

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}

+ Response 200 (application/json)

    + Body
    
            {
                "results": [
                    {
                        "city": "广州",
                        "watts": 1000,
                        "capacity": 100,
                        "name": "my_socket",
                        "objectId": "5424c7b358ebfc3ec01cbf5d",
                        "did": "z9fJgw6LeZBsuFeV9PMbLA",
                        "updatedAt": "2014-09-26T01:57:23.189Z",
                        "createdAt": "2014-09-26T01:56:03.266Z"
                    }
                ]
            }


## 设备信息 [/1/classes/device_info/{objectId}]

+ Parameters
    + objectId (required, string, `Ed1nuqPvcm`)

### 修改设备信息 [PUT]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {
              "city": "广州"
            }

+ Response 200 (application/json)

    + Body
    
            {
              "updatedAt": "2011-08-20T02:06:57.931Z"
            }
